### ISSUE TITLE
No label displayed on Android with react native v 0.41

### ISSUE THREAD

**Issue by nocmar** [thegamenicorus/react-native-flexi-radio-button#2]
The label of radio button (text) is not displayed. The reason might be breaking changes from version 0.36 of react native:
https://github.com/facebook/react-native/releases/tag/v0.36.0

**Comment by thegamenicorus** [comment]
https://github.com/thegamenicorus/react-native-flexi-radio-button/pull/3
Thank you.

**Comment by dibelogrivaya** [comment]
I have the same problem ("react-native": "0.59.8", "react-native-flexi-radio-button": "^0.2.2")

**iOS:**

<img width="450" alt="Screen Shot 2019-06-26 at 11 45 55 AM" src="https://user-images.githubusercontent.com/1580342/60165522-20440600-9808-11e9-893a-4f29b4c99e66.png">


**Android:**

![tempFileForShare_20190626-114440](https://user-images.githubusercontent.com/1580342/60165585-36ea5d00-9808-11e9-9a94-aa59fd17beef.jpg)
