### ISSUE TITLE
I want to change the style inside the border of the radio button.

### ISSUE THREAD

**Issue by okayu8** [thegamenicorus/react-native-flexi-radio-button#28]
I want to change the background color inside the circle of the radio button.
I was able to change the color of the dot when I selected it using the provided properties. Also, we could change the color of the radio button border.
However, you can not change the color inside the border. The background color outside the circle will be applied.

I can use methods other than using properties. Is it possible to realize the above?

**Comment by asimkhan0** [comment]
@thegamenicorus @okayu8 have added this circle background color prop. please have a look at this pull request.

https://github.com/thegamenicorus/react-native-flexi-radio-button/pull/29

**Comment by okayu8** [comment]
Sorry for my late reply.
I was able to solve with your answer.
