### ISSUE TITLE
Is there a way to change outer radio circle's color? 

### ISSUE THREAD

**Issue by bexoss** [thegamenicorus/react-native-flexi-radio-button#6]
First Thanks for making this. 

Okay there is a option to change radio dot, using `color` into RadioButton element. 
But how about outer radio circle's color? 
Actually what I'm trying to do is 
![cap1](https://cloud.githubusercontent.com/assets/12633102/24695472/f4dc20a4-1a20-11e7-8477-b0d881ac2424.PNG)

gray color to unselected item, blue color to selected item. 
Is there a way to do it?

**Comment by thegamenicorus** [comment]
Hello @bexoss 

You can upgrade react-native-flexi-radio-button to v. 0.1.9
I've add 'activeColor' to RadioGroup in this version.
From your example, you can code like these::

```jsx
<RadioGroup 
    //...other props
    color = 'grey'
    activeColor = 'blue'
>
   //...radio buttons
</RadioGroup>
```
Thank you for your request.
Enjoy coding :)

**Comment by bexoss** [comment]
@thegamenicorus Thanks to quick update! You are awesome!
