### ISSUE TITLE
one problem

### ISSUE THREAD

**Issue by RamirezET** [thegamenicorus/react-native-flexi-radio-button#8]
I think you forget this (    
componentWillReceiveProps(nextProps) {
        this.setState({
            selectedIndex: nextProps.selectedIndex
        })
    }
    ),on radioGroup.js

**Comment by thegamenicorus** [comment]
updated on [ef5d5c7](https://github.com/thegamenicorus/react-native-flexi-radio-button/commit/ef5d5c7c0c118a0a1aaec2cacc29ccf513a0672e)

Thank you for your support 👍
