### ISSUE TITLE
How will i unselect the radio button

### ISSUE THREAD

**Issue by sumit-khajanchi** [thegamenicorus/react-native-flexi-radio-button#9]
Hi There,

I am using react-native-flexi-radio-button how can I unselect the radio button. In my case, i am using the radio button like this
`
<RadioGroup thickness={2}  color='#5f5f5f' selectedIndex={this.state.selectedAnswer} onSelect=
  {(index, value) => this.onSelect(index, value)}> {
     this.state.options.map((option, index) => (
         <RadioButton key={`${index}`} value={option.answer} color={'#5f5f5f'} style={{margin: 5, alignItems:'center'}}>
               <Text style={{marginLeft: 5}}> {option.title} </Text>
         </RadioButton>
      ))
   }
</RadioGroup>
`

and when I am changing the option value on the same screen with the previous value of radio button is selected. I am also set the selectedAnswer value null `this.setState({selectedAnswer: null})` but no success. 
how can I resolve this? Please help me with this

**Comment by thegamenicorus** [comment]
hello @sumit-khajanchi 
You can upgrade react-native-flexi-radio-button to v. 0.2.0

and this code
> this.setState({selectedAnswer: null})

will be working.

Thank you.
Cheer 👍

**Comment by sumit-khajanchi** [comment]
Thanks, It's working the way I want.
